### ISSUE TITLE
Linear Quick Issue with Characters and Stars

### ISSUE THREAD

**Issue by sashton045** [DorkmasterFlek/smrpg_web_randomizer#53]
Console or Emulator:
I am playing on Snes9X v1.53

Description of problem:
I am playing a linear game with the quick preset, with the addition of flags "Cp" and "Ef." I just defeated Bowyer in the Forest, and I received Mallow into my party at his normal level instead of matched to the area. I had received Bowser into my party first, with him at his normal level, as well. Also, upon defeating Mack and Bowyer, I also didn't receive stars in my inventory, with no option on the "X" menu to view stars, either
![Capture](https://user-images.githubusercontent.com/50972409/58295406-1cead400-7d9d-11e9-8bd7-ea519c7af70e.PNG)
![Capture2](https://user-images.githubusercontent.com/50972409/58295416-1fe5c480-7d9d-11e9-971d-e76e6953799b.PNG)

**Comment by pidgezero-one** [comment]
Mallow's original starting level is 2, not 3. A roll of 3 at forest maze is just bad luck. Additionally, the Quick preset uses the R flag, meaning Mack and Bowyer are not guaranteed to give you star pieces.

**Comment by sashton045** [comment]
He was at level two when the fight started, but leveled up due to the
reward from the fight.

So does the linear mode still randomize the star piece locations? Because
there's no option on the website to change that flag with Linear mode.

**Comment by pidgezero-one** [comment]
Oops, sorry, I missed the part where you said you were playing on linear! Linear shouldn't randomize star pieces, no.

**Comment by DorkmasterFlek** [comment]
It should not, no.  But you said you're playing on Snes9x 1.53 which I believe is the problem.  The How To Play section of the site on emulators mentions using 1.56 or later only for Snes9x.  Anything prior to 1.56 does not emulate the SA-1 chip properly.  I'm 99% sure that's the issue here, as nobody else has reported this issue with linear mode and there have been at least a few people playing it.

I'll keep this issue open for the moment, but can you please try a more recent version of Snes9x and let us know if this issue persists?

**Comment by sashton045** [comment]
So I figured I should try a new seed, and upon accepting "Mallow" into my party, I received Toadstool as the party member at level 9. I don't remember for sure, but I believe that is her normal level. I have upgraded my snes9x to v1.56.2, as well. Will play through further to see if there are any other bugs
![Capture](https://user-images.githubusercontent.com/50972409/58335483-aaffa280-7e0f-11e9-8ec7-1edb8ea2c352.PNG)
![Capture2](https://user-images.githubusercontent.com/50972409/58335484-aaffa280-7e0f-11e9-919e-b2cd4e3fecc1.PNG)

**Comment by DorkmasterFlek** [comment]
Do you have the permalink or seed number for that?

**Comment by sashton045** [comment]
Mode: Linear
Version: 8.1.2
Flags: Cspjl Sc4 -freeshops Edfsa Qsba X3
Seed: 3049525423
File Select Character: Mario
File Select Hash: CLERK / MAGMUS / CULEX / MOKURA

**Comment by sashton045** [comment]
I encountered the issue of not receiving a star when I should be again. I just defeated Mack, and I didn't get the animation for receiving a star, and there's no option in the menu to view the stars
![Capture4](https://user-images.githubusercontent.com/50972409/58337868-bb664c00-7e14-11e9-9ae6-4019974e261c.PNG)
![Capture5](https://user-images.githubusercontent.com/50972409/58337869-bb664c00-7e14-11e9-948c-d4826c7a2076.PNG)
![Capture3](https://user-images.githubusercontent.com/50972409/58337870-bb664c00-7e14-11e9-9a8f-81c6caa69f29.PNG)

**Comment by sashton045** [comment]
Getting to the Bowyer fight, I got Mallow in my party again, and he is underleveled for the area again. He started at level 3 before beating Bowyer, and leveled up to 4. I also did not receive a star from the fight, either
![Capture6](https://user-images.githubusercontent.com/50972409/58341090-6bd74e80-7e1b-11e9-954c-d99a1dbeb757.PNG)
![Capture7](https://user-images.githubusercontent.com/50972409/58341091-6bd74e80-7e1b-11e9-9707-1903ab8ac2a4.PNG)

**Comment by DorkmasterFlek** [comment]
Okay I'll look into it, thank you.

**Comment by DorkmasterFlek** [comment]
There was indeed an issue with the starting levels getting clobbered with some of the open mode changes, thanks for bringing that to our attention.  I pushed a hotfix for this so it should be resolved now.

The star piece cutscenes are not a bug, they were removed along with most of the cutscenes in the game.  They're present in open mode because the point is hunting down the star piece locations so you need to know when you find one.  In linear mode, this is unnecessary since the progression is fixed and the game ends when you beat Smithy.

**Comment by sashton045** [comment]
Ah okay, I understand now. Thanks a lot!
