### ISSUE TITLE
Web Interface: Palette Swap doesn't show up on Linear Mode

### ISSUE THREAD

**Issue by SoraHjort** [DorkmasterFlek/smrpg_web_randomizer#62]
Palette Swap only shows up in Open World mode. It disappears when selecting Linear. Other options do disappear, but I figured that is likely because those randomization options do not work well in Linear as compared to Open. Palette however is cosmetic, thus shouldn't be of any affect on which mode selected.

**Comment by DorkmasterFlek** [comment]
You'd think that, but the linear mode patch is kind of a mess due to the only SMRPG ROM editor available and it's the legacy mode that isn't being worked on any further.  In theory the palette changes *should* work with that patch as well but the sprite data is very sensitive to changes.  I'll test this on our beta branch while we're developing new features for the main open world mode, but if it causes problems this won't be added.

**Comment by SoraHjort** [comment]
Ahhh, ok, I didn't realize linear mode was like that. You might consider having a note that shows up when selecting Linear that it isn't currently/no longer supported to prevent this confusion.

**Comment by DorkmasterFlek** [comment]
Fair enough, I'll try to make that more clear with the wording.

**Comment by DorkmasterFlek** [comment]
This appears to work okay in linear mode.  It will be included in the next release.
