### ISSUE TITLE
Water Glitching Out

### ISSUE THREAD

**Issue by newgamespage** [DorkmasterFlek/smrpg_web_randomizer#63]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator: zsnesw151

 If emulator state which emulator and version.  If console, state which flash cart firmware.

Flags (paste flag string if available): Ks Rk Cjl Tc4 M2 Sb4 Ef B Qa P1 Nbmq D4s 

Description of problem: Water flickers blindingly and/or is covered by a flat texture in Midas River, Rose Way, and Tadpole Pond.

**Comment by newgamespage** [comment]
Also: Game softlocked when I tried to switch Amulet and Scrooge Ring on Mario in Equip Menu while in Forest Maze boss room after unlocking Mario in that fight.

**Comment by DorkmasterFlek** [comment]
That's because you're using zsnes.  This emulator uses various speed hacks that don't emulate things properly, and doesn't handle SA-1 games properly at all.  It's completely banned in any speedrunning activities for this reason.  We recommend snes9x as the easiest emulator to use that works properly on the latest version.  Try this or one of the recommended emulators from the site: https://randomizer.smrpgspeedruns.com/how-to-play
